- repository: autowarefoundation/autoware
  files:
    - source: .github/dependabot.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/spell-check.yaml
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
