name: create_prs_for_vcs_repositories_update
description: 'Create PRs for VCS repositories update'

inputs:
  token:
    description: 'GitHub token'
    required: true
  repo_name:
    description: 'Repository name'
    required: true
  parent_dir:
    description: 'Parent directory'
    required: false
    default: './'
  base_branch:
    description: 'Base branch'
    required: false
    default: 'main'
  new_branch_prefix:
    description: 'New branch prefix. The branch name will be "<new_branch_prefix>-<user_name>/<repository_name>/<new_version>".'
    required: false
    default: 'feat/update-'
  autoware_repos_file_name:
    description: 'Autoware repositories file name'
    required: false
    default: 'autoware.repos'
  verbosity:
    description: 'Verbosity level'
    required: false
    default: 0

runs:
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        architecture: "x64"
        
    - name: Install dependencies
      shell: bash
      run: python -m pip install --upgrade ruamel.yaml PyGithub GitPython packaging

    - name: Set git config
      uses: autowarefoundation/autoware-github-actions/set-git-config@v1
      with:
        token: ${{ inputs.token }}

    - name: Fetch all branches
      shell: bash
      run: git fetch --all

    - name: Run Python
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        VERBOSITY=""
        for i in $(seq 1 ${{ inputs.verbosity }}); do
          VERBOSITY="$VERBOSITY -v"
        done
        python ${GITHUB_ACTION_PATH}/create_prs_for_vcs_repositories_update.py
        --repo_name ${{ inputs.repo_name }} \
        --parent_dir ${{ inputs.parent_dir }} \
        --base_branch ${{ inputs.base_branch }} \
        --new_branch_prefix ${{ inputs.new_branch_prefix }} \
        --autoware_repos_file_name ${{ inputs.autoware_repos_file_name }} \
        $VERBOSITY