name: clang-tidy
description: ""

inputs:
  rosdistro:
    description: ""
    required: true
  clang-tidy-config-url:
    description: ""
    required: true
  target-packages:
    description: ""
    required: true
  build-depends-repos:
    description: ""
    required: false
  cmake-build-type:
    description: ""
    required: false
    default: Release
  token:
    description: ""
    required: false
    default: ${{ github.token }}
  include-eol-distros:
    description: ""
    required: false
  cache-key-element:
    description: Will be part of the cache key
    default: default
    required: false

runs:
  using: composite
  steps:
    - name: Show targets
      run: |
        echo "target packages: ${{ inputs.target-packages }}"
      shell: bash

    - name: Install curl
      run: |
        sudo apt-get -yqq update
        sudo apt-get -yqq install curl
      shell: bash

    - name: Install pip for rosdep
      run: |
        sudo apt-get -yqq update
        sudo apt-get -yqq install python3-pip
      shell: bash

    - name: Install ament_clang_tidy
      run: |
        sudo apt-get -yqq update
        sudo apt-get -yqq install ros-${{ inputs.rosdistro }}-ament-clang-tidy libomp-dev
      shell: bash

    - name: Set git config
      if: ${{ inputs.build-depends-repos != ''}}
      uses: autowarefoundation/autoware-github-actions/set-git-config@v1
      with:
        token: ${{ inputs.token }}

    - name: Clone dependency packages
      if: ${{ inputs.build-depends-repos != ''}}
      run: |
        mkdir -p dependency_ws
        vcs import dependency_ws < ${{ inputs.build-depends-repos }}
      shell: bash

    - name: Run rosdep install
      run: |
        package_paths=$(colcon list -p --packages-above-and-dependencies ${{ inputs.target-packages }} --base-paths . dependency_ws)
        sudo apt-get -yqq update
        if [ "${{ inputs.include-eol-distros }}" = "true" ]; then
            rosdep update --include-eol-distros
        else
            rosdep update
        fi
        DEBIAN_FRONTEND=noninteractive rosdep install -yqq --from-paths ${package_paths} --ignore-src --rosdistro ${{ inputs.rosdistro }}
      shell: bash

    - name: Restore build files from cache
      id: restore-build-files
      uses: actions/cache/restore@v4
      with:
        path: |
          ./build
          ./install
        key: build-${{ runner.arch }}-${{ inputs.rosdistro }}-${{ inputs.cache-key-element }}-${{ inputs.cmake-build-type }}-${{ github.sha }}

    - name: Build
      if: ${{ steps.restore-build-files.outputs.cache-hit != 'true' }}
      run: |
        . /opt/ros/${{ inputs.rosdistro }}/setup.sh
        colcon build --event-handlers console_cohesion+ \
          --packages-up-to ${{ inputs.target-packages }} \
          --cmake-args -DCMAKE_BUILD_TYPE=${{ inputs.cmake-build-type }} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      shell: bash

    - name: Retrieve .clang-tidy
      run: |
        curl -fsSL -o .clang-tidy ${{ inputs.clang-tidy-config-url }} \
          -H "Authorization: token ${{ inputs.token }}"
      shell: bash

    - name: Analyze
      if: ${{ inputs.target-packages != '' }}
      run: |
        mkdir /tmp/clang-tidy-result
        ament_clang_tidy --export-fixes /tmp/clang-tidy-result/fixes.yaml --packages-select ${{ inputs.target-packages }} --jobs $(nproc) > /tmp/clang-tidy-result/report.txt || true
        echo "${{ github.event.number }}" > /tmp/clang-tidy-result/pr-id.txt
        echo "${{ github.event.pull_request.head.repo.full_name }}" > /tmp/clang-tidy-result/pr-head-repo.txt
        echo "${{ github.event.pull_request.head.ref }}" > /tmp/clang-tidy-result/pr-head-ref.txt
      shell: bash

    - name: Check if the report.txt file exists
      id: check-report-txt-existence
      uses: autowarefoundation/autoware-github-actions/check-file-existence@v1
      with:
        files: /tmp/clang-tidy-result/report.txt

    - name: Check if the fixes.yaml file exists
      id: check-fixes-yaml-existence
      uses: autowarefoundation/autoware-github-actions/check-file-existence@v1
      with:
        files: /tmp/clang-tidy-result/fixes.yaml

    - name: Upload artifacts
      if: ${{ steps.check-report-txt-existence.outputs.exists == 'true' && steps.check-fixes-yaml-existence.outputs.exists == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: clang-tidy-result
        path: /tmp/clang-tidy-result/

    - name: Mark the workflow as failed if clang-tidy find an error
      if: ${{ steps.check-report-txt-existence.outputs.exists == 'true' }}
      run: |
        if [ -n "$(grep ": error:" /tmp/clang-tidy-result/report.txt)" ]; then
          exit 1
        fi
      shell: bash
