name: get-docs-version-name
description: Get the version name of the docs

outputs:
  version-name:
    description: The version name of the docs
    value: ${{ jobs.get-docs-version-name.outputs.version-name }}

runs:
  using: composite
  steps:
    - name: Set version name (push)
      if: ${{ !github.event.pull_request }}
      run: |
        echo "VERSION_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      shell: bash

    - name: Set version name (pull_request)
      if: ${{ github.event.pull_request }}
      run: |
        echo "VERSION_NAME=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      shell: bash

    - name: Set output
      id: get-docs-version-name
      run: |
        # Replace invalid character '/' by '-'
        echo ::set-output name=version-name::"${VERSION_NAME/\//-}"
      shell: bash

    - name: Show result
      run: |
        echo "self packages: ${{ steps.get-docs-version-name.outputs.version-name }}"
      shell: bash
