name: spell-check
description: ""

inputs:
  cspell-json-url:
    description: ""
    required: true
  token:
    description: ""
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Retrieve spell check dictionary
      run: |
        curl -fsSL -o .cspell.json ${{ inputs.cspell-json-url }} \
          -H "Authorization: token ${{ inputs.token }}"
      shell: bash

    - name: Run spell check
      uses: streetsidesoftware/cspell-action@v2
      with:
        config: .cspell.json
