name: get-self-packages
description: Get the list of self packages

outputs:
  self-packages:
    description: List of self packages
    value: ${{ steps.get-self-packages.outputs.self-packages }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get packages in this repository
      id: get-self-packages
      run: |
        echo ::set-output name=self-packages::$(colcon list --names-only)
      shell: bash

    - name: Show result
      run: |
        echo "self packages: ${{ steps.get-self-packages.outputs.self-packages }}"
      shell: bash
