name: colcon-test
description: ""

inputs:
  rosdistro:
    description: ""
    required: true
  target-packages:
    description: ""
    required: true
  packages-skip:
    description: Packages to skip during testing
    required: false
    default: ""
  build-depends-repos:
    description: ""
    required: false
  packages-above-repos:
    description: ""
    required: false
  token:
    description: ""
    required: false
    default: ${{ github.token }}
  include-eol-distros:
    description: ""
    required: false
  underlay-workspace:
    description: Path to the underlay workspace containing setup.sh
    default: ""
    required: false
  use-local-mixin:
    description: Will use the local mixin repository to avoid rate limits
    default: false
    required: false
outputs:
  coverage-report-files:
    description: ""
    value: ${{ steps.test.outputs.coverage-reports }}

runs:
  using: composite
  steps:
    - name: Show target packages
      run: |
        echo "target packages: ${{ inputs.target-packages }}"
      shell: bash

    - name: Set up colcon-mixin
      if: ${{ inputs.use-local-mixin == 'false' }}
      run: |
        colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml || true
        colcon mixin update default
      shell: bash

    - name: Checkout mixin repo locally
      if: ${{ inputs.use-local-mixin == 'true' }}
      uses: actions/checkout@v6
      with:
        repository: colcon/colcon-mixin-repository
        path: colcon-mixin-repository

    - name: Set up colcon-mixin (from local)
      if: ${{ inputs.use-local-mixin == 'true' }}
      run: |
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        INDEX="$GITHUB_WORKSPACE/colcon-mixin-repository/index.yaml"

        # Remove existing mixin repo if it exists
        colcon mixin remove default || echo "default mixin not previously added"

        # Add local mixin repo
        colcon mixin add default file://"$INDEX"

        # This reads the mixin files from the local clone, no HTTP
        colcon mixin update default
      shell: bash

    - name: Install packages for coverage commands
      run: |
        sudo apt-get -yqq update
        sudo apt-get -yqq install \
          lcov \
          python3-pip \
          python3-colcon-coveragepy-result \
          python3-colcon-lcov-result \
          python3-pytest-cov
      shell: bash

    - name: Set git config
      if: ${{ inputs.build-depends-repos != '' || inputs.packages-above-repos != '' }}
      uses: autowarefoundation/autoware-github-actions/set-git-config@v1
      with:
        token: ${{ inputs.token }}

    - name: Clone dependency packages
      if: ${{ inputs.build-depends-repos != '' }}
      run: |
        mkdir -p dependency_ws
        vcs import dependency_ws < ${{ inputs.build-depends-repos }}
      shell: bash

    - name: Clone above dependency packages
      if: ${{ inputs.packages-above-repos != '' }}
      run: |
        mkdir -p dependency_ws
        vcs import dependency_ws < ${{ inputs.packages-above-repos }}
      shell: bash

    - run: sudo apt-get -yqq update
      shell: bash

    - name: Ensure rosdep directory exists
      run: mkdir -p ~/.ros/rosdep
      shell: bash

    - name: Restore rosdep cache
      id: rosdep-restore
      uses: actions/cache/restore@v5
      with:
        path: ~/.ros/rosdep
        key: rosdep-${{ runner.arch }}-${{ inputs.rosdistro }}

    - name: Check rosdep cache age
      id: check-cache
      run: |
        timestamp_file=~/.ros/rosdep/CACHE_TIMESTAMP
        ttl=$(( 3 * 3600 ))  # 3 hours
        if [ -f "$timestamp_file" ]; then
          age=$(( $(date +%s) - $(cat "$timestamp_file") ))
          echo "Cache age is $age seconds"
          [ "$age" -gt "$ttl" ] && echo "stale=true" >> $GITHUB_OUTPUT || echo "stale=false" >> $GITHUB_OUTPUT
        else
          echo "No timestamp file found. Treating cache as stale."
          echo "stale=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Run rosdep update (if stale)
      if: steps.check-cache.outputs.stale == 'true'
      id: rosdep-update
      run: |
        echo "Running rosdep update..."
        if [ "${{ inputs.include-eol-distros }}" = "true" ]; then
          rosdep update --include-eol-distros
        else
          rosdep update
        fi
        date +%s > ~/.ros/rosdep/CACHE_TIMESTAMP
      shell: bash
      continue-on-error: true

    - name: Save rosdep cache
      if: steps.check-cache.outputs.stale == 'true' && steps.rosdep-update.outcome == 'success'
      uses: actions/cache/save@v5
      with:
        path: ~/.ros/rosdep
        key: rosdep-${{ runner.arch }}-${{ inputs.rosdistro }}

    - name: Run rosdep install
      run: |
        package_paths=$(colcon list -p --packages-above-and-dependencies ${{ inputs.target-packages }} --base-paths . dependency_ws)
        if [ -f "${{ inputs.underlay-workspace }}/setup.sh" ]; then
          . ${{ inputs.underlay-workspace }}/setup.sh
        fi
        DEBIAN_FRONTEND=noninteractive rosdep install -yqq --from-paths ${package_paths} --ignore-src --rosdistro ${{ inputs.rosdistro }}
      shell: bash

    - name: Test
      run: |
        set -e
        . /opt/ros/${{ inputs.rosdistro }}/setup.sh
        if [ -f "${{ inputs.underlay-workspace }}/setup.sh" ]; then
          . ${{ inputs.underlay-workspace }}/setup.sh
        fi

        # Build skip packages argument if packages-skip is provided
        skip_packages_arg=""
        if [ -n "${{ inputs.packages-skip }}" ]; then
          skip_packages_arg="--packages-skip ${{ inputs.packages-skip }}"
        fi

        colcon lcov-result --zero-counters \
          --verbose \
          --packages-above ${{ inputs.target-packages }} \
          $skip_packages_arg

        colcon lcov-result --initial \
          --verbose \
          --packages-above ${{ inputs.target-packages }} \
          $skip_packages_arg

        colcon test --event-handlers console_cohesion+ \
          --mixin coverage-pytest \
          --packages-above ${{ inputs.target-packages }} \
          $skip_packages_arg \
          --executor sequential \
          --return-code-on-test-failure

        colcon lcov-result \
          --verbose \
          --filter "*/test/*" \
          --packages-above ${{ inputs.target-packages }} \
          $skip_packages_arg || true

        colcon coveragepy-result \
          --verbose \
          --packages-above ${{ inputs.target-packages }} \
          $skip_packages_arg || true
      shell: bash

    - name: Check if the lcov coverage file exists
      id: lcov-coverage-file-existence
      uses: autowarefoundation/autoware-github-actions/check-file-existence@v1
      with:
        files: lcov/total_coverage.info

    - name: Check if the coveragepy coverage file exists
      id: coveragepy-coverage-file-existence
      uses: autowarefoundation/autoware-github-actions/check-file-existence@v1
      with:
        files: coveragepy/.coverage

    - name: Generate output
      id: test
      run: |
        coverage_files=()
        if [[ "${{ steps.lcov-coverage-file-existence.outputs.exists }}" == "true" ]]; then
          coverage_files+=("lcov/total_coverage.info")
        fi

        if [[ "${{ steps.coveragepy-coverage-file-existence.outputs.exists}}" == "true" ]]; then
          coverage_files+=("coveragepy/.coverage")
        fi

        # Join coverage file names
        coverage_files_str="$(IFS=,; echo "${coverage_files[*]}")"
        echo "coverage-reports=$coverage_files_str" >> $GITHUB_OUTPUT
      shell: bash
