name: register-autonomoustuff-repository
description: ""

inputs:
  rosdistro:
    description: ""
    required: true

runs:
  using: composite
  steps:
    # https://github.com/astuff/pacmod3_msgs#installation
    - name: Register apt repository
      run: |
        sudo apt-get -yqq update
        sudo apt-get -yqq install apt-transport-https
        sudo sh -c 'echo "deb [trusted=yes] https://s3.amazonaws.com/autonomoustuff-repo/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/autonomoustuff-public.list'
        sudo apt-get -yqq update
      shell: bash

    #  https://github.com/astuff/docker-builds/blob/e9f563ef04b0578ba0b545711ea3e41b20a51d27/ros2/foxy/ros-core/Dockerfile#L29
    - name: Register rosdep repository
      run: |
        echo "yaml https://s3.amazonaws.com/autonomoustuff-repo/autonomoustuff-public-${{ inputs.rosdistro }}.yaml ${{ inputs.rosdistro }}" | sudo tee /etc/ros/rosdep/sources.list.d/40-autonomoustuff-public-${{ inputs.rosdistro }}.list > /dev/null
      shell: bash
