name: sync-branches
description: ""

inputs:
  token:
    description: ""
    required: true
  base-branch:
    description: ""
    required: true
  sync-pr-branch:
    description: ""
    required: true
  sync-target-repository:
    description: ""
    required: true
  sync-target-branch:
    description: ""
    required: true
  pr-title:
    description: ""
    required: true
  pr-labels:
    description: ""
    required: false
    default: ""
  pr-assignees:
    description: ""
    required: false
    default: ""
  pr-reviewers:
    description: ""
    required: false
    default: ""
  auto-merge-method:
    description: ""
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.base-branch }}
        fetch-depth: 0

    - name: Set git config
      uses: autowarefoundation/autoware-github-actions/set-git-config@v1
      with:
        token: ${{ inputs.token }}

    - name: register sync-target repository
      run: |
        git remote add sync-target "${{ inputs.sync-target-repository }}"
        git fetch -pPtf --all
      shell: bash

    - name: sync-target-branch is tag?
      id: target-is-tag
      run: |
        result=$(git tag | sed -n -E -e '/${{ inputs.sync-target-branch }}/p')
      shell: bash

    - name: Sync branches
      if: ${{ steps.target-is-tag.outputs.result == '' }}
      run: |
        git reset --hard "sync-target/${{ inputs.sync-target-branch }}"
      shell: bash

    - name: Sync tags
      if: ${{ steps.target-is-tag.outputs.result != '' }}
      run: |
        git reset --hard "${{ inputs.sync-target-branch }}"
      shell: bash

    - name: Remove sync-target-repository
      run: |
        git remote rm sync-target
      shell: bash

    - name: Generate changelog
      id: generate-changelog
      uses: autowarefoundation/autoware-github-actions/generate-changelog@v1
      with:
        git-cliff-args: origin/${{ inputs.base-branch }}..HEAD

    - name: Replace PR number to URL
      id: replace-pr-number-to-url
      run: |
        # Output multiline strings: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
        changelog=$(echo "$CHANGELOG" | sed -r "s|\(#([0-9]+)\)|("${REPO_URL%.git}"/pull/\1)|g")
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "changelog<<$EOF" >> $GITHUB_OUTPUT
        echo "$changelog" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
      env:
        CHANGELOG: ${{ steps.generate-changelog.outputs.changelog }}
        REPO_URL: ${{ inputs.sync-target-repository }}
      shell: bash

    - name: Create PR
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.token }}
        base: ${{ inputs.base-branch }}
        branch: ${{ inputs.sync-pr-branch }}
        title: ${{ inputs.pr-title }}
        body: ${{ steps.replace-pr-number-to-url.outputs.changelog }}
        labels: ${{ inputs.pr-labels }}
        assignees: ${{ inputs.pr-assignees }}
        reviewers: ${{ inputs.pr-reviewers }}
        author: github-actions <github-actions@github.com>
        signoff: true
        delete-branch: true

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
      shell: bash

    - name: Enable auto-merge
      if: ${{ inputs.auto-merge-method != '' && steps.create-pr.outputs.pull-request-operation == 'created' }}
      run: gh pr merge --${{ inputs.auto-merge-method }} --auto "${{ steps.create-pr.outputs.pull-request-number }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
