name: sync-branches
description: ""

inputs:
  token:
    description: ""
    required: true
  base-branch:
    description: ""
    required: true
  base-repo:
    description: ""
    required: false
  sync-pr-branch:
    description: ""
    required: true
  sync-target-repository:
    description: ""
    required: true
  sync-target-branch:
    description: ""
    required: true
  pr-title:
    description: ""
    required: true
  pr-labels:
    description: ""
    required: false
    default: ""
  pr-assignees:
    description: ""
    required: false
    default: ""
  pr-reviewers:
    description: ""
    required: false
    default: ""
  auto-merge-method:
    description: ""
    required: false
    default: ""
  pr-body-header:
    description: Text to prepend before the changelog in PR body
    required: false
    default: ""

outputs:
  pull-request-url:
    description: URL of the created pull request
    value: ${{ steps.create-pr.outputs.pull-request-url }}

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.base-repo || github.repository }}
        ref: ${{ inputs.base-branch }}
        fetch-depth: 0
        token: ${{ inputs.token }}

    - name: Set git config
      uses: autowarefoundation/autoware-github-actions/set-git-config@v1
      with:
        token: ${{ inputs.token }}

    - name: Sync branches
      run: |
        git remote add sync-target "${{ inputs.sync-target-repository }}"
        git fetch -pPtf --all
        git reset --hard "sync-target/${{ inputs.sync-target-branch }}"
        git remote rm sync-target
      shell: bash

    - name: Generate changelog
      id: generate-changelog
      uses: autowarefoundation/autoware-github-actions/generate-changelog@v1
      with:
        git-cliff-args: origin/${{ inputs.base-branch }}..HEAD

    - name: Prepare PR body
      id: prepare-pr-body
      run: |
        # Replace PR numbers with URLs
        changelog=$(echo "$CHANGELOG" | sed -r "s|\(#([0-9]+)\)|("${REPO_URL%.git}"/pull/\1)|g")

        # Output multiline strings: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "body<<$EOF" >> $GITHUB_OUTPUT
        if [ -n "$PR_BODY_HEADER" ]; then
          echo "$PR_BODY_HEADER" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
        fi
        echo "$changelog" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
      env:
        PR_BODY_HEADER: ${{ inputs.pr-body-header }}
        CHANGELOG: ${{ steps.generate-changelog.outputs.changelog }}
        REPO_URL: ${{ inputs.sync-target-repository }}
      shell: bash

    - name: Create PR
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.token }}
        base: ${{ inputs.base-branch }}
        branch: ${{ inputs.sync-pr-branch }}
        title: ${{ inputs.pr-title }}
        body: ${{ steps.prepare-pr-body.outputs.body }}
        labels: ${{ inputs.pr-labels }}
        assignees: ${{ inputs.pr-assignees }}
        reviewers: ${{ inputs.pr-reviewers }}
        author: github-actions <github-actions@github.com>
        signoff: true
        delete-branch: true

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
      shell: bash

    - name: Enable auto-merge
      if: ${{ inputs.auto-merge-method != '' && steps.create-pr.outputs.pull-request-operation == 'created' }}
      run: gh pr merge --${{ inputs.auto-merge-method }} --auto "${{ steps.create-pr.outputs.pull-request-number }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
