name: pre-commit-autoupdate
description: ""

inputs:
  token:
    description: ""
    required: true
  pre-commit-config:
    description: ""
    required: true
  pr-base:
    description: ""
    required: false
    default: ${{ github.event.repository.default_branch }}
  pr-branch:
    description: ""
    required: false
    default: pre-commit-autoupdate
  pr-title:
    description: ""
    required: false
    default: "ci(pre-commit): autoupdate"
  pr-commit-message:
    description: ""
    required: false
    default: "ci(pre-commit): autoupdate"
  pr-labels:
    description: ""
    required: false
    default: ""
  pr-assignees:
    description: ""
    required: false
    default: ""
  pr-reviewers:
    description: ""
    required: false
    default: ""
  auto-merge-method:
    description: ""
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install pre-commit
      run: |
        python -m pip install pre-commit
      shell: bash

    - name: Run pre-commit
      run: |
        pre-commit autoupdate --config ${{ inputs.pre-commit-config }}
      shell: bash

    - name: Create PR
      id: create-pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.token }}
        base: ${{ inputs.pr-base }}
        branch: ${{ inputs.pr-branch }}
        title: ${{ inputs.pr-title }}
        commit-message: ${{ inputs.pr-commit-message }}
        body: ${{ steps.create-pr-body.outputs.body }}
        labels: ${{ inputs.pr-labels }}
        assignees: ${{ inputs.pr-assignees }}
        reviewers: ${{ inputs.pr-reviewers }}
        signoff: true
        delete-branch: true

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
      shell: bash

    - name: Enable auto-merge
      if: ${{ inputs.auto-merge-method != '' && steps.create-pr.outputs.pull-request-operation == 'created' }}
      run: gh pr merge --${{ inputs.auto-merge-method }} --auto "${{ steps.create-pr.outputs.pull-request-number }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
